owner: vajradog
repo: chitstat

sites:
  - name: Chitta Website
    url: https://chitta.app
    
  - name: Chitta API - Health Check
    url: https://chitta.app/api/health

status-website:
  name: Chitta Status
  # Remove the logo url line if you don't have a logo yet
  # logoUrl: https://chitta.app/logo.png
  
  # Intro section
  introTitle: "**Chitta** System Status"
  introMessage: Real-time monitoring of Chitta services — your AI companion for studying Tibetan Buddhist texts
  
  # Navigation
  navbar:
    - title: Status
      href: /
    - title: Chitta.app
      href: https://chitta.app
    - title: GitHub
      href: https://github.com/vajradog/chitstat
  
  # Remove the default repository text
  repo: ""
  
  # Custom theme colors (optional)
  theme: light
  
  # Remove "powered by" and other branding
  i18n:
    footer: Monitoring powered by GitHub Actions
    title: Chitta Status
    url: https://chitta.app

# Disable assignees
assignees:
  - vajradog

# Update check frequency (every 5 minutes by default)
workflowSchedule:
  uptime: "*/5 * * * *"
