owner: vajradog
repo: chitstat

sites:
  - name: Chitta Website
    url: https://chitta.app
    
  - name: Chitta API - Health Check
    url: https://chitta.app/api/health
    expectedStatusCodes:
      - 200
      - 503  # May return 503 if services degraded

status-website:
  # Remove the cname line below if you DON'T want a custom domain
  # cname: status.chitta.app
  name: Chitta Status
  introTitle: "Chitta System Status"
  introMessage: Real-time status and uptime monitoring for Chitta services
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://chitta.app

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
