# Change these first
owner: vajradog # Your GitHub organization or username, where this repository lives
repo: chitstat # The name of this repository

sites:
  - name: Chitta Website
    url: https://chitta.app
    
  - name: Chitta API - Chat
    url: https://chitta.app/api/chat
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"messages":[{"role":"user","content":"test"}],"textSlug":"test"}'
    expectedStatusCodes:
      - 200
      - 401  # Expected if no auth
      
  - name: Supabase
    url: https://lwdoqpnlxwjsgtttmlro.supabase.co

status-website:
  cname: status.chitta.app  # Optional: use custom domain
  name: Chitta Status
  introTitle: "Chitta System Status"
  introMessage: Real-time status and uptime monitoring for Chitta services
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://chitta.app

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
